In [1]:
#パッケージのインポート
import numpy as np
import math

In [2]:
#各関数の定義
def sigmoid(u):
    return 1/(1+np.exp(-u))

def softmax(u):
    e = np.exp(u)
    return e/np.sum(e)

#順伝搬の計算の定義
def forward(x):
    global W1
    global W2
    u1 = x.dot(W1)
    z1 = sigmoid(u1)
    u2 = z1.dot(W2)
    y = softmax(u2)
    return y, z1

In [3]:
#各変数の定義
W1 = np.array([[0.1, 0.3], [0.2, 0.4]])
W2 = np.array([[0.1, 0.3], [0.2, 0.4]])

x = np.array([[1, 0.5]])
y, z1 = forward(x)

#出力
print(z1)
print(y)

[[0.549834   0.62245933]]
[[0.44165237 0.55834763]]


In [4]:
#誤差逆伝搬
def back_propagation(x, z1, y, d):
    global W1
    global W2
    delta2 = y-d
    grad_W2 = z1.T.dot(delta2)
    
    sigmoid_dash = z1 * (1-z1)
    delta1 = delta2.dot(W2.T) * sigmoid_dash
    grad_W1 = x.T.dot(delta1)
    
    W2 -= learning_rate * grad_W2
    W1 -= learning_rate * grad_W1

In [5]:
W1 = np.array([[0.1, 0.3], [0.2, 0.4]])
W2 = np.array([[0.1, 0.3], [0.2, 0.4]])
learning_rate = 0.005

# 順伝播
x = np.array([[1, 0.5]])
y, z1 = forward(x)

# 誤差逆伝播
d = np.array([[1, 0]]) 
back_propagation(x, z1, y, d)

print (W1)
print (W2)

[[0.0998618  0.29986879]
 [0.1999309  0.39993439]]
[[0.10153499 0.29846501]
 [0.20173774 0.39826226]]
