In [1]:
#使用パッケージのインポート
import numpy as np

In [2]:
#内積計算
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

answer = np.dot(a, b)
answer

array([[19, 22],
       [43, 50]])

In [3]:
#XとWの定義(2019/1/27)
x = np.array([1,2])
w = np.array([[1,3, 5], [2,4, 6]])

#有効グラフの定義
def directed_graph(x):
    return np.dot(x, w)

In [4]:
#出力
directed_graph(x)

array([ 5, 11, 17])

In [5]:
#XとW(重み)とB(誤差)の定義(2019/2/3)
#A(1) = X(1)W(1)+B(1)を実装する
X = np.array([5, 10])
W = np.array([[2, 2, 3], [5, 10, 8]])
B = np.array([1, 10, 100])

#有効グラフの定義
def directed_graph_2(X):
    A = np.dot(X, W) + B
    return A

In [6]:
#出力
directed_graph_2(X)

array([ 61, 120, 195])